services:  
  mongo-1:
    container_name: 'mongo-1'
    hostname: 'mongo-1'
    entrypoint: >
      /bin/bash -c '
      openssl rand -base64 756 > /data/keyfile.key &&
      chmod 400 /data/keyfile.key &&
      chown mongodb:mongodb /data/keyfile.key &&
      /usr/local/bin/docker-entrypoint.sh mongod --replSet rs0 --keyFile /data/keyfile.key --bind_ip_all'
    image: mongo:8.0
    ports:
      - 127.0.10.1:27017:27017
      - 28017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Abcd1234
      - MONGO_INITDB_DATABASE=myDatabase
    volumes:
        - 'mongo1data:/data/db'
        - 'mongo1config:/data/configdb'
        - 'sharedconfig:/data'
    healthcheck:
      test: mongosh
        -u $${MONGO_INITDB_ROOT_USERNAME}
        -p $${MONGO_INITDB_ROOT_PASSWORD}
        --eval "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo-1:27017',priority:1},{_id:1,host:'mongo-2:27017',priority:0.5},{_id:2,host:'mongo-3:27017',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    networks: 
      - "mongo-net"
    restart: unless-stopped

  mongo-2:
    container_name: "mongo-2"
    hostname: 'mongo-2'
    image: mongo:8.0
    ports:
        - 127.0.10.2:27017:27017
    volumes:
        - 'mongo2data:/data/db'
        - 'mongo2config:/data/configdb'
        - 'sharedconfig:/data'
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/keyfile.key"]
    networks: 
      - "mongo-net"
    restart: unless-stopped

  mongo-3:
    container_name: 'mongo-3'
    hostname: 'mongo-3'
    image: mongo:8.0
    ports:
       - 127.0.10.3:27017:27017
    volumes:
        - 'mongo3data:/data/db'
        - 'mongo3config:/data/configdb'
        - 'sharedconfig:/data'
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/keyfile.key"] 
    networks: 
      - "mongo-net"
    restart: unless-stopped

  express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:Abcd1234@mongo-1:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
    networks: 
      - "mongo-net"

# https://github.com/haohanyang/compass-web
  compass:
    image: haohanyang/compass-web
    container_name: compass
    environment:
      CW_MONGO_URI: mongodb://root:Abcd1234@mongo-1:27017/
    depends_on:
      - mongo-1
    ports:
      - 8080:8080
    networks:
      - "mongo-net"

volumes:
  mongo1data:
  mongo1config:
  mongo2data:
  mongo2config:
  mongo3data:
  mongo3config:
  sharedconfig:

networks:
  mongo-net:
    driver: bridge
